### ISSUE TITLE
Error running smalt map

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/snvphyl-galaxy#4]
I'm getting an error in the SNVPhyl at the smalt map step of the workflow.  I can't find too much info in the galaxy error log, however this is what I see from within galaxy:

<img width="1180" alt="Screen Shot 2019-05-14 at 12 46 24 PM" src="https://user-images.githubusercontent.com/824607/57733327-21ecac80-7654-11e9-9f9d-3e211e51a793.png">

Here are my installation details for smalt map:
<img width="1209" alt="Screen Shot 2019-05-14 at 2 36 52 PM" src="https://user-images.githubusercontent.com/824607/57734033-cde2c780-7655-11e9-851f-334113d8fc43.png">

As you're aware, we're using Galaxy 17.09 (patched with release_17.09, not the tag) and running SNVPhyl (package_snvphyl_1_8 and suite_snvphyl_1_0_1) from IRIDA 19.01.3. SNVPhyl works fine in IRIDA 0.22.0 + Galaxy 17.09 

@apetkau I believe you installed Galaxy 17.09 while helping us troubleshoot the AMR detection pipeline. If you still have it, could you confirm whether you see the same error?

**Comment by glwinsor** [comment]
I also see this message in the galaxy error log:

`galaxy.model.metadata DEBUG 2019-05-14 16:12:07,734 setting metadata externally failed for HistoryDatasetAssociation 3043: [Errno 2] No such file or dire
ctory
galaxy.jobs.runners ERROR 2019-05-14 16:12:07,842 (1327/21027551) Job wrapper finish method failed
Traceback (most recent call last):
  File "/project/6004808/irida/dev/galaxy-17.09/lib/galaxy/jobs/runners/__init__.py", line 630, in finish_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code)
  File "/project/6004808/irida/dev/galaxy-17.09/lib/galaxy/jobs/__init__.py", line 1290, in finish
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/project/6004808/irida/dev/galaxy-17.09/lib/galaxy/datatypes/binary.py", line 393, in set_meta
    exit_code = subprocess.call(args=command, stderr=open(stderr_name, 'wb'))
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
galaxy.tools.error_reports DEBUG 2019-05-14 16:12:08,125 Bug report plugin <galaxy.tools.error_reports.plugins.sentry.SentryPlugin object at 0x7fd0a12dff50> generated response None`

**Comment by apetkau** [comment]
Hello @glwinsor 

Sorry for the delay in getting back to you.

I believe the cause of the error is that you need both `samtools` and `bcftools` installed (or available) on your cluster nodes for Galaxy to do some post-processing of the output files after a tool is finished running.

The particular exception you listed points to this line of code in Galaxy <https://github.com/galaxyproject/galaxy/blob/v17.09/lib/galaxy/datatypes/binary.py#L393>. This tries to run the command `samtools index` on one of the output files. I can reproduce the same error by uninstalling `samtools` from my machine.

I believe `samtools` (along with `bcftools`) would need to be installed on the cluster nodes (as these are run on the cluster nodes following the run for the particular tool such as smalt). I had instructions in my install guide on setting up an environment (through the `env.sh` file) to make these available in conda <https://irida.corefacility.ca/documentation/administrator/galaxy/setup/#galaxy-web-server-environment>. Was there any changes that were made to how conda is setup/how environments are activated (or where conda is installed)? Maybe this is the cause of the particular issue.

**Comment by apetkau** [comment]
It also may just be the case that `samtools` and `bcftools` need to be installed on the Galaxy web server machine instead of the cluster nodes. So if that's easier, you could try this first and see if it works.

**Comment by glwinsor** [comment]
Thanks @apetkau I'll try the galaxy web server machine first. It'll probably take longer to get someone to install it on our nodes.
